flowchart TD
    IA[Inteligencia Artificial]
    
    IA --> Fuerte[Fuerte]
    IA --> Debil[Débil]
    
    Fuerte --> AGI[AGI (Inteligencia artificial general)]
    Fuerte --> Conciencia[Conciencia artificial]
    
    Debil --> ML[Machine Learning]
    Debil --> CV[Computer Vision]
    Debil --> NLP[Procesamiento de Lenguaje Natural]
    Debil --> Robotica[Robótica]
    Debil --> SE[Sistemas Expertos]
    
    ML --> Supervised[Aprendizaje Supervisado]
    ML --> Unsupervised[Aprendizaje No Supervisado]
    ML --> Reinforcement[Aprendizaje por Refuerzo]
    ML --> DL[Deep Learning]
    
    Supervised --> Arboles[Árboles de decisión]
    Supervised --> Regresion[Regresión]
    Supervised --> Clasificadores[Clasificadores]
    
    Unsupervised --> Clusterizacion[Clusterización]
    
    CV --> ImageRec[Reconocimiento de imágenes]
    CV --> VideoAnal[Análisis de video]
    CV --> FacialRec[Reconocimiento facial]
    
    NLP --> Comprension[Comprensión de texto]
    NLP --> Traduccion[Traducción automática]
    NLP --> ClasificadoresTexto[Clasificadores de texto]
    NLP --> SpeechRec[Reconocimiento de voz]
    
    Robotica --> Movimiento[Movimiento autónomo]
    Robotica --> Vehiculos[Vehículos autónomos]
    Robotica --> Industrial[Automatización industrial]
    
    SE --> Diagnosticos[Diagnósticos médicos]
    SE --> Pronostico[Pronóstico financiero]